### ISSUE TITLE
Controller 2's :start is called before Controller 1's :stop

### ISSUE THREAD

**Issue by dpetranek** [ingesolvoll/kee-frame#88]
I'm not actually sure if this is a bug, and I've got a very easy workaround, but I thought I'd ask:

I've got two controllers, and when navigating from a route controlled by controller 1 to a route controlled by controller 2, controller 2's :start fn is called before controller 1's :stop fn.

observed:
controller 2 :start -> controller 1 :stop 

expected:
controller 1 :stop -> controller 2 :start

I think a valid answer is that controllers fire independently and we can't rely on their order, but I'm curious if it would be possible to make this guarantee.

**Comment by ingesolvoll** [comment]
@dpetranek That's a good catch! I did a quick study of the source code, and seems like this is what happens:

https://github.com/ingesolvoll/kee-frame/blob/master/src/kee_frame/controller.cljc#L62

Controllers are stored as a list in an atom. Each one is checked on every route change, always in the same order. Not a particularly sophisticated implementation, and it seems consistent with your findings.

It could be straightforward fixing this, if we find it important, by doing the controller processing in 2 steps:
- Processing controller list for `:stop`
- Processing controller list for `:start`

Thoughts?

**Comment by dpetranek** [comment]
I think that's a great idea. I think guaranteeing all `:stop`s run before all `:start`s is sufficient to prevent confusion (and certainly would have prevented my issued). And I think explicitly not guaranteeing an order within those two categories is good, too.

The only tradeoff I see is performance, but I don't think it will be meaningfully slower. The worst case I can think of is an application with user generated routes, but the controller design is more than flexible enough that a single controller can manage many  routes, so I don't expect even large applications to have large numbers of controllers.

**Comment by dpetranek** [comment]
I think a note like this in the "Controller state transitions" section of the docs would be enough to explain the new behavior:

> There is no guarantee what order multiple controllers will be called in, save that `:stop` fns will be called before `:start` fns.

Just some spaghetti for the wall, feel free edit for clarity or any reason at all : )

**Comment by ingesolvoll** [comment]
@dpetranek This has been (almost) fixed in latest snapshot, by adding an intermediate dispatch that dispatches all starts after all stops have been dispatched. The fix has been done while making another change that removes use of `(f/dispatch [...])` in favor of `{:dispatch [...]}`. Internally in kee-frame that is. 

The main thing is that this introduces a (very minor) delay between stop-dispatches and start-dispatches. Not sure if this would be a problem or not. Don't really see an alternative because returning a `dispatch-n` list that contains stops first, then starts, doesn't really guarantee the order. Only a new animation frame would do that, I think.
